version: "3.3"
services:
    sapo_nginx:
      container_name: sapo_interview_nginx
      build: ./nginx/
      ports:
        - 9980:80
      volumes:
          - ./../backend/public/:/var/www/html/

    sapo_php:
      container_name: sapo_interview_php
      build: ./php/
      expose:
        - 9000
      volumes:
          - ./../backend/:/project/
          - ./../backend/public/:/var/www/html/

      working_dir: /project/

    sapo_node:
      container_name: sapo_interview_node
      build: ./node/
      volumes:
        - ./../frontend/:/var/www/html/
      working_dir: /var/www/html/
      ports:
        - "8000:8000"
      tty: true

    sapo_mysql:
      container_name: sapo_interview_mysql
      image: mysql
      restart: always
      environment:
        MYSQL_DATABASE: 'database_1'
        MYSQL_USER: 'test_user'
        MYSQL_PASSWORD: 'test_password'
        MYSQL_ROOT_PASSWORD: 'root_password'
      ports:
        - 9906:3306
      volumes:
        - ./mysql/my-db:/var/lib/mysql